package lexicalAnalyze;

public enum TokenType {
	ORIGIN, SCALE, ROT, IS, TO, STEP, DRAW, FOR, FROM, PI, SIN, COS, T, SEMICO, L_BRACKET, 
	R_BRACKET, COMMA, PLUS, MINUS, MUL, DIV, POWER, FUNC, CONST_ID, NONTOKEN, ERRTOKEN, ID, EOF
}
